// nim-kit-vue-ui-h5/src/components/NEUIKit/Chat/message-read-info.vue
<template>
  <div class="msg-page-wrapper">
    <div class="msg-nav">
      <NavBar :title="t('msgReadPageTitleText')" :showLeft="true">
        <template v-slot:left>
          <div @click="backToConversation">
            <Icon type="icon-zuojiantou" :size="22"></Icon>
          </div>
        </template>
      </NavBar>
    </div>
    <div class="msg-alert">
      <NetworkAlert />
    </div>
    <div class="msg-read-header">
      <div
        class="msg-read-header-item"
        :class="selectedType === 'read' ? 'active' : ''"
        @click="selectedType = 'read'"
      >
        {{ `${t("readText")}(${readCount})` }}
      </div>
      <div
        class="msg-read-header-item"
        :class="selectedType === 'unread' ? 'active' : ''"
        @click="selectedType = 'unread'"
      >
        {{ `${t("unreadText")}(${unReadCount})` }}
      </div>
    </div>
    <div v-show="selectedType === 'read'" class="list-wrapper">
      <div
        v-if="readList.length"
        class="list-item"
        v-for="item in readList"
        :key="item"
      >
        <div class="avatar-wrapper">
          <Avatar
            size="40"
            :account="item"
            :goto-user-card="true"
            :teamId="teamId"
            :goto-team-card="false"
          />
        </div>
        <Appellation :account="item" :teamId="teamId"></Appellation>
      </div>
      <div v-else>
        <Empty :text="t('allUnReadText')"></Empty>
      </div>
    </div>
    <div v-show="selectedType === 'unread'" class="list-wrapper">
      <div
        v-if="unReadList.length"
        class="list-item"
        v-for="item in unReadList"
        :key="item"
      >
        <div class="avatar-wrapper">
          <Avatar
            size="40"
            :account="item"
            :goto-user-card="true"
            :teamId="teamId"
            :goto-team-card="false"
          />
        </div>
        <Appellation :account="item" :teamId="teamId"></Appellation>
      </div>
      <div v-else>
        <Empty :text="t('allReadText')"></Empty>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
/** 消息已读未读详情页面 */
import { onMounted, ref } from "vue";
import NetworkAlert from "../CommonComponents/NetworkAlert.vue";
import NavBar from "./message/nav-bar.vue";
import Icon from "../CommonComponents/Icon.vue";
import { t } from "../utils/i18n";
import Avatar from "../CommonComponents/Avatar.vue";
import Appellation from "../CommonComponents/Appellation.vue";
import Empty from "../CommonComponents/Empty.vue";
import { useRouter } from "vue-router";
import { getCurrentInstance } from "vue";

const readCount = ref(0);
const unReadCount = ref(0);
const readList = ref<string[]>([]);
const unReadList = ref<string[]>([]);
const selectedType = ref<string>("read");
const teamId = ref<string>("");
const router = useRouter();

const { proxy } = getCurrentInstance()!;
const store = proxy?.$UIKitStore;
const nim = proxy?.$NIM;
const backToConversation = () => {
  router.back();
};

onMounted(() => {
  const messageClientId = router.currentRoute.value.query
    ?.messageClientId as string;
  const conversationId = router.currentRoute.value.query
    ?.conversationId as string;
  if (messageClientId && conversationId) {
    teamId.value =
      nim.V2NIMConversationIdUtil.parseConversationTargetId(conversationId);
    const msg =
      store && store.msgStore.getMsg(conversationId, [messageClientId]);
    if (msg?.length) {
      // 获取当前消息的已读未读详情
      store?.msgStore.getTeamMessageReceiptDetailsActive(msg[0]).then((res) => {
        readCount.value = res?.readReceipt.readCount;
        unReadCount.value = res?.readReceipt.unreadCount;
        readList.value = res?.readAccountList;
        setTimeout(() => {
          unReadList.value = res?.unreadAccountList;
        });
      });
    }
  }
});
</script>

<style scoped>
.msg-page-wrapper {
  display: flex;
  flex-direction: column;
  height: 100%;
  box-sizing: border-box;
  background-color: #fff;
}
.msg-nav {
  flex-basis: 45px;
}
.msg-read-header {
  display: flex;
  align-items: center;
  width: 100%;
  height: 40px;
  margin-top: 5px;
}
.msg-read-header-item {
  flex: 1;
  text-align: center;
  line-height: 40px;
  color: #000;
  margin-bottom: 10px;
}
.active {
  border-bottom: 1px solid #007aff;
}
.list-wrapper {
  flex: 1;
  overflow-x: hidden;
  overflow-y: auto;
}
.list-item {
  height: 50px;
  width: 100%;
  overflow: hidden;
  display: flex;
  align-items: center;
  padding: 0 20px;
}
.avatar-wrapper {
  margin-right: 10px;
}
</style>

// nim-kit-react-ui-h5/src/NEUIKit/chat/message-read-info/index.tsx
import React, { useState, useEffect } from 'react'
import { useLocation, useNavigate } from '@/utils/router'
import { useTranslation } from '@/NEUIKit/common/hooks/useTranslate'
import { useStateContext } from '@/NEUIKit/common/hooks/useStateContext'

import NetworkAlert from '@/NEUIKit/common/components/NetworkAlert'
import NavBar from '@/NEUIKit/chat/message/nav-bar'
import Icon from '@/NEUIKit/common/components/Icon'
import Avatar from '@/NEUIKit/common/components/Avatar'
import Appellation from '@/NEUIKit/common/components/Appellation'
import Empty from '@/NEUIKit/common/components/Empty'

import './index.less'

/**
 * 消息已读未读详情页面
 */
const MessageReadInfo: React.FC = () => {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const location = useLocation()
  const { store, nim } = useStateContext()

  const [readCount, setReadCount] = useState(0)
  const [unReadCount, setUnReadCount] = useState(0)
  const [readList, setReadList] = useState<string[]>([])
  const [unReadList, setUnReadList] = useState<string[]>([])
  const [selectedType, setSelectedType] = useState<'read' | 'unread'>('read')

  // 获取要编辑的字段key（从URL参数中）
  const query = new URLSearchParams(location.search)
  const messageClientId: string = query.get('messageClientId') || ''
  const conversationId: string = query.get('conversationId') || ''
  const teamId = nim.V2NIMConversationIdUtil.parseConversationTargetId(conversationId)
  const msg = store.msgStore.getMsg(conversationId, [messageClientId])?.[0]

  /**
   * 初始化数据
   */
  useEffect(() => {
    if (msg) {
      // 获取当前消息的已读未读详情
      store?.msgStore.getTeamMessageReceiptDetailsActive(msg).then((res) => {
        setReadCount(res?.readReceipt.readCount || 0)
        setUnReadCount(res?.readReceipt.unreadCount || 0)
        setReadList(res?.readAccountList || [])

        setUnReadList(res?.unreadAccountList || [])
      })
    }
  }, [msg])

  /**
   * 返回到会话页面
   */
  const backToConversation = () => {
    navigate(-1)
  }

  return (
    <div className="msg-page-wrapper">
      <div className="msg-nav">
        <NavBar
          title={t('msgReadPageTitleText')}
          showLeft={true}
          leftContent={
            <div onClick={backToConversation}>
              <Icon type="icon-zuojiantou" size={22} />
            </div>
          }
        />
      </div>

      <div className="msg-alert">
        <NetworkAlert />
      </div>

      <div className="msg-read-header">
        <div className={`msg-read-header-item ${selectedType === 'read' ? 'active' : ''}`} onClick={() => setSelectedType('read')}>
          {`${t('readText')}(${readCount})`}
        </div>
        <div className={`msg-read-header-item ${selectedType === 'unread' ? 'active' : ''}`} onClick={() => setSelectedType('unread')}>
          {`${t('unreadText')}(${unReadCount})`}
        </div>
      </div>

      {/* 已读列表 */}
      <div className="list-wrapper" style={{ display: selectedType === 'read' ? 'block' : 'none' }}>
        {readList.length > 0 ? (
          readList.map((item) => (
            <div className="list-item" key={item}>
              <div className="avatar-wrapper">
                <Avatar size={40} account={item} gotoUserCard={true} teamId={teamId} />
              </div>
              <Appellation account={item} teamId={teamId} />
            </div>
          ))
        ) : (
          <Empty text={t('allUnReadText')} />
        )}
      </div>

      {/* 未读列表 */}
      <div className="list-wrapper" style={{ display: selectedType === 'unread' ? 'block' : 'none' }}>
        {unReadList.length > 0 ? (
          unReadList.map((item) => (
            <div className="list-item" key={item}>
              <div className="avatar-wrapper">
                <Avatar size={40} account={item} gotoUserCard={true} teamId={teamId} />
              </div>
              <Appellation account={item} teamId={teamId} />
            </div>
          ))
        ) : (
          <Empty text={t('allReadText')} />
        )}
      </div>
    </div>
  )
}

export default MessageReadInfo
