// nim-kit-react-ui-h5/src/layouts/tabBar.tsx
import React, { useEffect, useState } from 'react'
import { NavLink } from '@/utils/router'
import { observer } from 'mobx-react-lite'
import { autorun } from 'mobx'
import { t } from '@/NEUIKit/common/utils/i18n'
import { useStateContext } from '@/NEUIKit/common/hooks/useStateContext'

// 导入图标
import conversationIcon from '@/NEUIKit/static/conversation.png'
import conversationSelectedIcon from '@/NEUIKit/static/conversation-selected.png'
import contactsIcon from '@/NEUIKit/static/contact.png'
import contactsSelectedIcon from '@/NEUIKit/static/contact-selected.png'
import meIcon from '@/NEUIKit/static/me.png'
import meSelectedIcon from '@/NEUIKit/static/me-selected.png'

import './tabBar.less'

/**
 * TabBar 组件 - 底部导航栏
 */
const TabBar: React.FC = observer(() => {
  const { store } = useStateContext()

  const [conversationUnread, setConversationUnread] = useState(false)
  const [contactsUnread, setContactsUnread] = useState(false)

  // 监听未读消息变化
  useEffect(() => {
    const disposer = autorun(() => {
      // 判断是否是云端会话
      const enableV2CloudConversation = store.sdkOptions?.enableV2CloudConversation

      // 会话未读数
      setConversationUnread(enableV2CloudConversation ? !!store.conversationStore?.totalUnreadCount : !!store.localConversationStore?.totalUnreadCount)

      // 通讯录验证消息未读数
      setContactsUnread(!!store.sysMsgStore.getTotalUnreadMsgsCount())
    })

    return () => disposer()
  }, [store.conversationStore?.totalUnreadCount, store.localConversationStore?.totalUnreadCount, store.sysMsgStore.getTotalUnreadMsgsCount()])

  return (
    <nav className="tab-bar-wrapper">
      <NavLink to="/conversation" className="tab-item">
        {({ isActive }) => (
          <div className="tab-item-content">
            <div className="icon-wrapper">
              <img src={isActive ? conversationSelectedIcon : conversationIcon} className="tab-icon" alt="message" />
              {conversationUnread && <span className="unread-dot"></span>}
            </div>
            <span>{t('messageText')}</span>
          </div>
        )}
      </NavLink>

      <NavLink to="/contacts" className="tab-item">
        {({ isActive }) => (
          <div className="tab-item-content">
            <div className="icon-wrapper">
              <img src={isActive ? contactsSelectedIcon : contactsIcon} className="tab-icon" alt="contacts" />
              {contactsUnread && <span className="unread-dot"></span>}
            </div>
            <span>{t('contactText')}</span>
          </div>
        )}
      </NavLink>

      <NavLink to="/my" className="tab-item">
        {({ isActive }) => (
          <div className="tab-item-content">
            <img src={isActive ? meSelectedIcon : meIcon} className="tab-icon" alt="my" />
            <span>{t('mineText')}</span>
          </div>
        )}
      </NavLink>
    </nav>
  )
})

export default TabBar

// nim-kit-vue-ui-h5/src/components/TabBar.vue
<template>
  <nav class="tabbar" v-if="showTabBar">
    <router-link to="/conversation" class="tab-item">
      <div class="tab-item-content">
        <div class="icon-wrapper">
          <img
            :src="
              $route.path === '/conversation'
                ? conversationSelectedIcon
                : conversationIcon
            "
            class="tab-icon"
          />
          <span v-if="conversationUnread" class="unread-dot"></span>
        </div>
        <span>{{ t("messageText") }}</span>
      </div>
    </router-link>
    <router-link to="/contacts" class="tab-item">
      <div class="tab-item-content">
        <div class="icon-wrapper">
          <img
            :src="
              $route.path === '/contacts' ? contactsSelectedIcon : contactsIcon
            "
            class="tab-icon"
          />
          <span v-if="contactsUnread" class="unread-dot"></span>
        </div>
        <span>{{ t("contactText") }}</span>
      </div>
    </router-link>
    <router-link to="/my" class="tab-item">
      <div class="tab-item-content">
        <img
          :src="$route.path === '/my' ? meSelectedIcon : meIcon"
          class="tab-icon"
        />
        <span>{{ t("mineText") }}</span>
      </div>
    </router-link>
  </nav>
</template>

<script setup lang="ts">
import { onMounted, computed, ref, getCurrentInstance } from "vue";
import { useRoute } from "vue-router";
import conversationIcon from "./NEUIKit/static/conversation.png";
import conversationSelectedIcon from "./NEUIKit/static/conversation-selected.png";
import contactsIcon from "./NEUIKit/static/contact.png";
import contactsSelectedIcon from "./NEUIKit/static/contact-selected.png";
import meIcon from "./NEUIKit/static/me.png";
import meSelectedIcon from "./NEUIKit/static/me-selected.png";
import RootStore from "@xkit-yx/im-store-v2";
import { autorun } from "mobx";
import { t } from "./NEUIKit/utils/i18n";
const route = useRoute();

const showTabBar = computed(() => {
  const allowedRoutes = ["/conversation", "/contacts", "/my"];
  return allowedRoutes.includes(route.path);
});
const conversationUnread = ref(false);
const contactsUnread = ref(false);
const { proxy } = getCurrentInstance()!;
const store = proxy?.$UIKitStore as RootStore;

onMounted(() => {
  autorun(() => {
    // 会话未读数，去掉 !!就是实际未读数
    /**是否是云端会话 */
    const enableV2CloudConversation =
      store?.sdkOptions?.enableV2CloudConversation;

    conversationUnread.value = enableV2CloudConversation
      ? !!store?.conversationStore?.totalUnreadCount
      : !!store?.localConversationStore?.totalUnreadCount;

    // 通讯录验证消息未读数
    contactsUnread.value = !!store?.sysMsgStore.getTotalUnreadMsgsCount();
  });
});
</script>

<style scoped>
.tabbar {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  height: 60px;
  display: flex;
  background-color: #fff;
  border-top: 1px solid #eee;
  z-index: 999;
}

.tab-item {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  color: #666;
  text-decoration: none;
  -webkit-tap-highlight-color: transparent; /* 添加这行 */
}
.tab-item-content {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.tab-item.router-link-active {
  color: #409eff;
}

.icon-wrapper {
  position: relative;
  display: inline-block;
  height: 24px;
}

.unread-dot {
  position: absolute;
  top: -2px;
  right: -2px;
  width: 8px;
  height: 8px;
  background-color: #ff4d4f;
  border-radius: 50%;
}

.tab-icon {
  width: 24px;
  height: 24px;
  margin-bottom: 2px;
}

.tab-item span {
  font-size: 12px;
}
</style>
