// nim-kit-react-ui-h5/src/NEUIKit/common/components/NavBar/index.tsx
import React, { ReactNode } from 'react'
import { useNavigate } from '@/utils/router'
import Icon from '../Icon'
import './index.less'

export interface NavBarProps {
  title?: string
  subTitle?: string
  backgroundColor?: string
  showLeft?: boolean
  leftContent?: ReactNode
  rightContent?: ReactNode
  iconContent?: ReactNode
  onBack?: () => void
}

const NavBar: React.FC<NavBarProps> = ({
  title = '',
  subTitle = '',
  backgroundColor = '#ffffff',
  showLeft = false,
  leftContent,
  rightContent,
  iconContent,
  onBack
}) => {
  const navigate = useNavigate()

  // 处理返回事件
  const handleBack = () => {
    if (onBack) {
      onBack()
    } else {
      navigate(-1)
    }
  }

  return (
    <div className="nav-bar-wrapper">
      <div
        className="nav-bar-container"
        style={{
          backgroundColor,
          height: '48px',
          alignItems: 'center'
        }}
      >
        {/* 左侧内容 */}
        {showLeft ? (
          leftContent
        ) : (
          <div className="nav-left" onClick={handleBack}>
            <Icon type="icon-zuojiantou" size={24} />
          </div>
        )}

        {/* 中间标题 */}
        <div className="title-container">
          <div className="title">{title}</div>
          {subTitle && <div className="subTitle">{subTitle}</div>}
          {iconContent}
        </div>

        {/* 右侧内容 */}
        <div className="nav-right">{rightContent}</div>
      </div>
      <div className="block"></div>
    </div>
  )
}

export default NavBar

// nim-kit-vue-ui-h5/src/components/NEUIKit/Chat/message/nav-bar.vue
<template>
  <div>
    <div
      class="nav-bar-wrapper"
      :style="{
        backgroundColor: backgroundColor || '#ffffff',
        backgroundImage: `url(${title})`,
        height: '50px',
        alignItems: 'center',
      }"
    >
      <slot v-if="showLeft" name="left"></slot>
      <div v-else @click="back">
        <Icon type="icon-zuojiantou" :size="22"></Icon>
      </div>
      <div class="title-container">
        <div class="title">{{ title }}</div>
        <div class="subTitle" v-if="subTitle">{{ subTitle }}</div>
        <slot name="icon"></slot>
      </div>
      <div>
        <slot name="right"></slot>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import Icon from "../../CommonComponents/Icon.vue";

withDefaults(
  defineProps<{
    title: string;
    subTitle?: string;
    backgroundColor?: string;
    showLeft?: boolean;
  }>(),
  {
    subTitle: "",
    backgroundColor: "",
    showLeft: true,
  }
);

const back = () => {};
</script>

<style scoped>
/* 导航栏容器 */
.nav-bar-wrapper {
  display: flex;
  justify-content: space-between;
  padding: 10px;
  z-index: 9999;
  color: #000;
}

/* 标题容器 */
.title-container {
  position: absolute;
  left: 50%;
  transform: translateX(-50%);
  width: 230px;
  display: flex;
  justify-content: center;
  align-items: center;
}

/* 主标题 */
.title {
  overflow: hidden;
  text-overflow: ellipsis;
  text-align: center;
  white-space: nowrap;
  font-weight: 500;
  font-size: 16px;
}

/* 副标题 */
.subTitle {
  white-space: nowrap;
  font-weight: 500;
}
</style>
