// nim-kit-vue-ui-h5/src/components/NEUIKit/User/aboutNetease.vue
<template>
  <div class="wrapper">
    <NavBar title="关于" />
    <div class="logo-box">
      <img
        src="https://yx-web-nosdn.netease.im/common/fcd2d5e8d2897d4b2d965e06509f47d2/about-logo.png"
        class="logo-img"
      />
      <div>{{ t("appText") }}</div>
    </div>
    <div class="aboutInfo-item-wrapper">
      <div class="item">
        <div>{{ t("uikitVersion") }}</div>
        <div>10.0.0</div>
      </div>
      <div class="item">
        <div>{{ t("IMVersion") }}</div>
        <div>{{ imPkg.version }}</div>
      </div>
      <a
        :href="yunxinWebsite"
        :showUnderLine="false"
        color="#000000"
        target="_blank"
        rel="noopener noreferrer"
        class="item"
      >
        <div>{{ t("productInfoText") }}</div>
        <Icon iconClassName="icon-arrow" type="icon-jiantou"></Icon>
      </a>
    </div>
  </div>
</template>

<script lang="ts" setup>
import NavBar from "../CommonComponents/NavBar.vue";
import { t } from "../utils/i18n";
//@ts-ignore
import imPkg from "nim-web-sdk-ng/package.json";

import Icon from "../CommonComponents/Icon.vue";
const yunxinWebsite = "https://yunxin.163.com/";
</script>

<style scoped>
.wrapper {
  background-color: rgb(245, 246, 247);
  background-color: #fff;
  width: 100%;
  height: 100vh;
  box-sizing: border-box;
}
.logo-box {
  text-align: center;
  margin: 22px auto;
  font-size: 20px;
  font-weight: 600;
  color: #000;
}
.logo-img {
  width: 72px;
  height: 72px;
}

.aboutInfo-item-wrapper .item {
  display: flex;
  justify-content: space-between;
  padding: 12px 20px 12px 0;
  margin-left: 20px;
  font-size: 14px;
  color: #000;
  font-weight: normal;
  border-bottom: 1px solid #f5f8fc;
}
</style>

// nim-kit-react-ui-h5/src/NEUIKit/user/about-netease/index.tsx
import React from 'react'
import NavBar from '@/NEUIKit/common/components/NavBar'
import Icon from '@/NEUIKit/common/components/Icon'
import { useTranslation } from '@/NEUIKit/common/hooks/useTranslate'
import { useNavigate } from '@/utils/router'
import imPkg from 'nim-web-sdk-ng/package.json'
import pkg from '../../../../package.json'
import './index.less'

// 由于无法直接导入SDK的package.json，这里使用一个假版本号
// 实际项目中应该动态获取或从环境变量中读取
const SDK_VERSION = imPkg.version
const UIKIT_VERSION = pkg.version
const YUNXIN_WEBSITE = 'https://yunxin.163.com/'

/**
 * 关于网易云信页面
 */
const AboutNetease: React.FC = () => {
  const { t } = useTranslation()
  const navigate = useNavigate()

  // 处理返回按钮点击
  const handleBack = () => {
    navigate(-1)
  }

  return (
    <div className="about-netease-wrapper">
      <NavBar title={t('commsEaseText')} onBack={handleBack} />

      {/* Logo区域 */}
      <div className="about-logo-box">
        <img src="https://yx-web-nosdn.netease.im/common/fcd2d5e8d2897d4b2d965e06509f47d2/about-logo.png" className="about-logo-img" alt="网易云信Logo" />
        <div>{t('appText')}</div>
      </div>

      {/* 信息列表 */}
      <div className="about-info-item-wrapper">
        {/* UIKit版本 */}
        <div className="about-item">
          <div>{t('uikitVersion')}</div>
          <div>{UIKIT_VERSION}</div>
        </div>

        {/* IM SDK版本 */}
        <div className="about-item">
          <div>{t('IMVersion')}</div>
          <div>{SDK_VERSION}</div>
        </div>

        {/* 产品信息链接 */}
        <a href={YUNXIN_WEBSITE} target="_blank" rel="noopener noreferrer" className="about-item">
          <div>{t('productInfoText')}</div>
          <Icon iconClassName="about-icon-arrow" type="icon-jiantou" />
        </a>
      </div>
    </div>
  )
}

export default AboutNetease
